Mon May 18 07:56:33 CDT 2020 : Servidor de red Apache Derby: Se ha iniciado 10.11.1.2 - (1629631) y está listo para aceptar las conexiones en el puerto 1527
----------------------------------------------------------------
Mon May 18 07:56:34 CDT 2020:
 Iniciando instancia a816c00e-0172-27db-735a-fffff529ba40 de Derby, versión The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): 
en el directorio de base de datos C:\Users\usuario\Documents\Brayan\Universidad\Universidad politecnica\Semestre No. 4\Programación III\Proyecto\Biblioteca\Biblioteca\BDBiblioteca\Biblioteca_Proyecto\Biblioteca_Proyecto con el cargador de clases sun.misc.Launcher$AppClassLoader@6f94fa3e
Cargado desde file:/C:/Program%20Files/Java/jdk1.8.0_131/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_131-b11
user.dir=C:\Program Files\Java\jdk1.8.0_131\db
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=C:\Users\usuario\Documents\Brayan\Universidad\Universidad politecnica\Semestre No. 4\Programación III\Proyecto\Biblioteca\Biblioteca\BDBiblioteca\Biblioteca_Proyecto
Cargador de clases de base de datos iniciado - derby.database.classpath=''
----------------------------------------------------------------
Mon May 18 07:56:43 CDT 2020:
Cerrando la instancia a816c00e-0172-27db-735a-fffff529ba40 en el directorio de base de datos C:\Users\usuario\Documents\Brayan\Universidad\Universidad politecnica\Semestre No. 4\Programación III\Proyecto\Biblioteca\Biblioteca\BDBiblioteca\Biblioteca_Proyecto\Biblioteca_Proyecto con cargador de clases sun.misc.Launcher$AppClassLoader@6f94fa3e
Mon May 18 07:56:43 CDT 2020 Thread[DRDAConnThread_2,5,main] (DATABASE = Biblioteca_Proyecto), (DRDAID = {2}), Cierre de la base de datos 'Biblioteca_Proyecto'.
----------------------------------------------------------------
Mon May 18 07:56:47 CDT 2020:
 Iniciando instancia a65c80ac-0172-27db-735a-fffff529ba40 de Derby, versión The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): 
en el directorio de base de datos C:\Users\usuario\Documents\Brayan\Universidad\Universidad politecnica\Semestre No. 4\Programación III\Proyecto\Biblioteca\Biblioteca\BDBiblioteca\Biblioteca_Proyecto\Biblioteca_Proyecto con el cargador de clases sun.misc.Launcher$AppClassLoader@6f94fa3e
Cargado desde file:/C:/Program%20Files/Java/jdk1.8.0_131/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_131-b11
user.dir=C:\Program Files\Java\jdk1.8.0_131\db
os.name=Windows 7
os.arch=amd64
os.version=6.1
derby.system.home=C:\Users\usuario\Documents\Brayan\Universidad\Universidad politecnica\Semestre No. 4\Programación III\Proyecto\Biblioteca\Biblioteca\BDBiblioteca\Biblioteca_Proyecto
Cargador de clases de base de datos iniciado - derby.database.classpath=''
Mon May 18 07:57:49 CDT 2020 Thread[DRDAConnThread_2,5,main] (XID = 235), (SESSIONID = 2), (DATABASE = Biblioteca_Proyecto), (DRDAID = {4}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR 08004: Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Mon May 18 07:57:49 CDT 2020 Thread[DRDAConnThread_2,5,main] (DATABASE = Biblioteca_Proyecto), (DRDAID = {4}), Se ha producido un fallo de autenticación de conexión. Motivo: Autenticación no válida..
----------------------------------------------------------------
Mon May 18 07:58:22 CDT 2020: cerrando motor de Derby
